# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveSmallIntegerField()),
                ('sample_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.SamplePack')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together=set([('sample_pack', 'id_number')]),
        ),
    ]
