# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20161212_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('sample_type', models.CharField(choices=[('ki', 'Kick'), ('sn', 'Snare'), ('un', 'Unknown')], default='un', max_length=2)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Kit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('kit', 'path')]),
        ),
    ]
