# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20161212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='path',
            field=models.FilePathField(max_length=200),
        ),
    ]
