# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20161212_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loudness', models.FloatField()),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Sample')),
            ],
        ),
    ]
