# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20161212_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='loudness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='spectral_flux',
            field=models.FloatField(),
        ),
    ]
