# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20161212_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='equal_loudness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
