# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_analysis_equal_loudness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='spectral_flux',
        ),
        migrations.AddField(
            model_name='analysis',
            name='rms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_centroid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_kurtosis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='temporal_centroid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
