# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20170108_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_centroid_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='spectral_centroid_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplepack',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samplepack',
            name='tags',
            field=models.ManyToManyField(related_name='samples_packs', to='analysis.Tag'),
        ),
    ]
