# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20170115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='onset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
