# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_sample_exclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='onset',
        ),
        migrations.AddField(
            model_name='sample',
            name='end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='onset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
