# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20170131_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='end',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='onset',
            new_name='stop_time',
        ),
    ]
