# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20170131_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='pitch_salience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
