# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_analysis_pitch_salience'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepack',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
