# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_samplepack_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepack',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
