# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20170215_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisz',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='analysisz',
            name='spectral_centroid_1',
        ),
        migrations.RemoveField(
            model_name='analysisz',
            name='spectral_centroid_2',
        ),
    ]
