# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_analysisrobustscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='outlier',
            field=models.BooleanField(default=False),
        ),
    ]
