# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_analysis_outlier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='loudness',
        ),
    ]
