# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_pca'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCA',
            new_name='AnalysisPCA',
        ),
    ]
