# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_auto_20170309_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepack',
            name='info_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
