# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_auto_20170309_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfcc_1_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_2_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_3_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_4_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_5_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_6_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_7_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_8_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_9_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_10_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_11_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_12_mean', models.FloatField(blank=True, null=True)),
                ('mfcc_13_mean', models.FloatField(blank=True, null=True)),
                ('temporal_centroid', models.FloatField(blank=True, null=True)),
                ('rms', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Sample')),
            ],
        ),
    ]
