# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_analysisfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfull',
            name='pitch_salience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_centroid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_complexity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_crest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_middle_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_middle_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_flatness_db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_flux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_kurtosis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_rms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_rolloff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_skewness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_spread',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_strongpeak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='window_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='zero_crossing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='analysisfull',
            unique_together=set([('sample', 'window_length')]),
        ),
    ]
