# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_auto_20170512_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfull',
            name='inharmonicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
