# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_auto_20170512_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfull',
            name='bark_10_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_11_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_12_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_13_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_14_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_15_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_16_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_17_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_18_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_19_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_1_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_20_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_21_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_22_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_23_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_24_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_25_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_26_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_27_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_2_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_3_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_4_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_5_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_6_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_7_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_8_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_9_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_kurtosis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_skewness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_spread',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='hfc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
