# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_auto_20170515_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfull',
            name='bark_10_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_11_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_12_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_13_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_14_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_15_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_16_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_17_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_18_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_19_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_1_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_20_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_21_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_22_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_23_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_24_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_25_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_26_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_27_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_2_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_3_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_4_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_5_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_6_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_7_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_8_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_9_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_kurtosis_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_skewness_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='bark_spread_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='hfc_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='inharmonicity_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='lat_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_10_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_11_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_12_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_13_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_1_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_2_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_3_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_4_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_5_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_6_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_7_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_8_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='mfcc_9_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='pitch_salience_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='rms_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_centroid_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_complexitpy_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_crest_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_decrease_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energy_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_high_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_low_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_middle_high_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_energyband_middle_low_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_flatness_db_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_flux_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_kurtosis_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_rms_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_rolloff_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_skewness_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_spread_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='spectral_strongpeak_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='temporal_centroid_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_1_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_2_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='tristimulus_3_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisfull',
            name='zero_crossing_rate_dev',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
