# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_auto_20170518_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisfull',
            old_name='spectral_complexitpy_dev',
            new_name='spectral_complexity_dev',
        ),
    ]
