# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_auto_20170518_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfull',
            name='window_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
