# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0044_auto_20171009_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysispca',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Sample'),
        ),
    ]
