# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_auto_20181201_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReduxManifold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_length', models.IntegerField(blank=True, null=True)),
                ('window_start', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(max_length=200)),
                ('dim_1', models.FloatField(blank=True, null=True)),
                ('dim_2', models.FloatField(blank=True, null=True)),
                ('dim_3', models.FloatField(blank=True, null=True)),
                ('dim_4', models.FloatField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Sample')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='isomap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='isomap',
            name='sample',
        ),
        migrations.AlterUniqueTogether(
            name='tsne',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tsne',
            name='sample',
        ),
        migrations.DeleteModel(
            name='ISOMAP',
        ),
        migrations.DeleteModel(
            name='TSNE',
        ),
        migrations.AlterUniqueTogether(
            name='reduxmanifold',
            unique_together=set([('sample', 'window_length', 'window_start')]),
        ),
    ]
