# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-01 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_auto_20181201_0443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReduxManifold',
            new_name='Manifold',
        ),
    ]
