# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_auto_20181201_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='analysisminmax',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='analysisz',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='analysispca',
            name='dim_5',
        ),
        migrations.RemoveField(
            model_name='analysispca',
            name='dim_6',
        ),
        migrations.RemoveField(
            model_name='analysispca',
            name='dim_7',
        ),
        migrations.RemoveField(
            model_name='analysispca',
            name='dim_8',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='AnalysisMinMax',
        ),
        migrations.DeleteModel(
            name='AnalysisZ',
        ),
    ]
