# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0052_auto_20181213_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCA',
            new_name='AnalysisPCA',
        ),
    ]
