# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_auto_20181213_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifold',
            name='method',
            field=models.CharField(choices=[('tnse', 'TNSE'), ('isomap', 'Isomap'), ('locally_linear', 'Locally Linear'), ('mds', 'MDS'), ('spectral', 'Spectral'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
