# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-14 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0056_auto_20181214_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCAStats',
            new_name='PCAStat',
        ),
    ]
