# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_auto_20181214_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200, unique=True)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('svc', models.FloatField(blank=True, null=True)),
                ('perceptron', models.FloatField(blank=True, null=True)),
                ('random_forest', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
