# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='sample_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='window_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='window_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='info',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('info', 'sample_type', 'window_length', 'window_start')]),
        ),
    ]
