
USE sample_analysis;

SELECT
    'Window (ms)',
    'Bark 1','Bark 2','Bark 3','Bark 4','Bark 5','Bark 6','Bark 7','Bark 8','Bark 9','Bark 10','Bark 11','Bark 12','Bark 13','Bark 14',
    'Bark 15','Bark 16','Bark 17','Bark 18','Bark 19','Bark 20','Bark 21','Bark 22','Bark 23','Bark 24','Bark 25','Bark 26','Bark 27',
    'Bark Kurtosis',
    'Bark Skewness',
    'Bark Spread',
    'HFC',
    'MFCC 1','MFCC 2','MFCC 3','MFCC 4','MFCC 5','MFCC 6','MFCC 7','MFCC 8','MFCC 9','MFCC 10','MFCC 11','MFCC 12','MFCC 13',
    'Temporal Centroid',
    'RMS',
    'LAT',
    'Zero Crossing Rate',
    'Pitch Salience',
    'Spectral Complexity',
    'Spectral Crest',
    'Spectral Decrease',
    'Spectral Energy',
    'Spectral Energy Band Low',
    'Spectral Energy Band MidLow',
    'Spectral Energy Band MidHigh',
    'Spectral Energy Band High',
    'Spectral Flatness dB',
    'Spectral Flux',
    'Spectral RMS',
    'Spectral Rolloff',
    'Spectral Strongpeak',
    'Inharmonicity',
    'Tristimulus 1', 'Tristimulus 2', 'Tristimulus 3',
    'Spectral Centroid',
    'Spectral Kurtosis',
    'Spectral Skewness',
    'Spectral Spread'

UNION ALL

SELECT
    a.window_length,
    variance(a.bark_1_mean),
    variance(a.bark_2_mean),
    variance(a.bark_3_mean),
    variance(a.bark_4_mean),
    variance(a.bark_5_mean),
    variance(a.bark_6_mean),
    variance(a.bark_7_mean),
    variance(a.bark_8_mean),
    variance(a.bark_9_mean),
    variance(a.bark_10_mean),
    variance(a.bark_11_mean),
    variance(a.bark_12_mean),
    variance(a.bark_13_mean),
    variance(a.bark_14_mean),
    variance(a.bark_15_mean),
    variance(a.bark_16_mean),
    variance(a.bark_17_mean),
    variance(a.bark_18_mean),
    variance(a.bark_19_mean),
    variance(a.bark_20_mean),
    variance(a.bark_21_mean),
    variance(a.bark_22_mean),
    variance(a.bark_23_mean),
    variance(a.bark_24_mean),
    variance(a.bark_25_mean),
    variance(a.bark_26_mean),
    variance(a.bark_27_mean),
    variance(a.bark_kurtosis),
    variance(a.bark_skewness),
    variance(a.bark_spread),
    variance(a.hfc),
    variance(a.mfcc_1_mean),
    variance(a.mfcc_2_mean),
    variance(a.mfcc_3_mean),
    variance(a.mfcc_4_mean),
    variance(a.mfcc_5_mean),
    variance(a.mfcc_6_mean),
    variance(a.mfcc_7_mean),
    variance(a.mfcc_8_mean),
    variance(a.mfcc_9_mean),
    variance(a.mfcc_10_mean),
    variance(a.mfcc_11_mean),
    variance(a.mfcc_12_mean),
    variance(a.mfcc_13_mean),
    variance(a.temporal_centroid),
    variance(a.rms),
    variance(a.lat),
    variance(a.zero_crossing_rate),
    variance(a.pitch_salience),
    variance(a.spectral_complexity),
    variance(a.spectral_crest),
    variance(a.spectral_decrease),
    variance(a.spectral_energy),
    variance(a.spectral_energyband_low),
    variance(a.spectral_energyband_middle_low),
    variance(a.spectral_energyband_middle_high),
    variance(a.spectral_energyband_high),
    variance(a.spectral_flatness_db),
    variance(a.spectral_flux),
    variance(a.spectral_rms),
    variance(a.spectral_rolloff),
    variance(a.spectral_strongpeak),
    variance(a.inharmonicity),
    variance(a.tristimulus_1),
    variance(a.tristimulus_2),
    variance(a.tristimulus_3),
    variance(a.spectral_centroid),
    variance(a.spectral_kurtosis),
    variance(a.spectral_skewness),
    variance(a.spectral_spread)


INTO OUTFILE '/Users/jshier/Development/School/jcura/sample_analysis/db_utils/output_full_var.csv'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
FROM analysis_analysisfull a 
    join analysis_sample s on a.sample_id=s.id 
    join analysis_kit k on s.kit_id=k.id 
    join analysis_samplepack p on k.sample_pack_id=p.id
WHERE
    s.exclude = 0 AND p.exclude = 0
GROUP BY
    a.window_length;
